#!/bin/bash
git submodule add git://github.com/kevinw/pyflakes-vim.git dotfiles-user/.vim/bundle/pyflakes-vim
git submodule add https://github.com/fholgado/minibufexpl.vim.git dotfiles-user/.vim/bundle/minibufexpl
git submodule add https://github.com/vim-scripts/taglist.vim.git dotfiles-user/.vim/bundle/taglist
git submodule add https://github.com/vim-scripts/gnupg.vim.git dotfiles-user/.vim/bundle/gnupg
git submodule add https://github.com/kien/ctrlp.vim dotfiles-user/.vim/bundle/ctrlp
git submodule add https://github.com/Rip-Rip/clang_complete.git dotfiles-user/.vim/bundle/clang_complete
git submodule add https://github.com/jnwhiteh/vim-golang dotfiles-user/.vim/bundle/vim-golang
git submodule add https://github.com/duff/vim-scratch dotfiles-user/.vim/bundle/vim-scratch
git submodule add https://github.com/benmills/vimux dotfiles-user/.vim/bundle/vimux
git submodule add https://github.com/vim-scripts/a.vim.git dotfiles-user/.vim/bundle/a.vim
git submodule add git://github.com/tpope/vim-commentary.git dotfiles-user/.vim/bundle/vim-commentary
git submodule add https://jgoulah@github.com/jgoulah/cocoa.vim.git dotfiles-user/.vim/bundle/cocoa.vim
git submodule add git://github.com/kortina/javaScriptLint.vim.git dotfiles-user/.vim/bundle/javaScriptLint
git submodule add git://github.com/nelstrom/vim-markdown-preview.git dotfiles-user/.vim/bundle/vim-markdown-preview
git submodule add git@github.com:kana/vim-fakeclip.git dotfiles-user/.vim/bundle/vim-fakeclip
git submodule add https://github.com/rkulla/pydiction dotfiles-user/.vim/bundle/pydiction
git submodule add git@github.com:nvie/vim-flake8.git dotfiles-user/.vim/bundle/vim-flake8
git submodule add git@github.com:rodjek/vim-puppet.git dotfiles-user/.vim/bundle/vim-puppet
git submodule add https://github.com/dcosson/vimux-nose-test2 dotfiles-user/.vim/bundle/vimux-nose-test2
git submodule add https://github.com/scrooloose/syntastic.git dotfiles-user/.vim/bundle/syntastic
git submodule add git@github.com:Lokaltog/powerline.git dotfiles-user/.vim/bundle/powerline
git submodule add git@github.com:tpope/vim-fugitive.git dotfiles-user/.vim/bundle/vim-fugitive
