#!/bin/bash
git submodule addgit://github.com/kevinw/pyflakes-vim.git vim/bundle/pyflakes-vim
git submodule addhttps://github.com/fholgado/minibufexpl.vim.git vim/bundle/minibufexpl
git submodule addhttps://github.com/vim-scripts/taglist.vim.git vim/bundle/taglist
git submodule addhttps://github.com/vim-scripts/gnupg.vim.git vim/bundle/gnupg
git submodule addhttps://github.com/kien/ctrlp.vim vim/bundle/ctrlp
git submodule addhttps://github.com/Rip-Rip/clang_complete.git vim/bundle/clang_complete
git submodule addhttps://github.com/jnwhiteh/vim-golang vim/bundle/vim-golang
git submodule addhttps://github.com/duff/vim-scratch vim/bundle/vim-scratch
git submodule addhttps://github.com/benmills/vimux vim/bundle/vimux
git submodule addhttps://github.com/vim-scripts/a.vim.git vim/bundle/a.vim
git submodule addgit://github.com/tpope/vim-commentary.git vim/bundle/vim-commentary
git submodule addhttps://jgoulah@github.com/jgoulah/cocoa.vim.git vim/bundle/cocoa.vim
git submodule addgit://github.com/kortina/javaScriptLint.vim.git vim/bundle/javaScriptLint
git submodule addgit://github.com/nelstrom/vim-markdown-preview.git vim/bundle/vim-markdown-preview
git submodule addgit@github.com:kana/vim-fakeclip.git vim/bundle/vim-fakeclip
git submodule addhttps://github.com/rkulla/pydiction vim/bundle/pydiction
git submodule addgit@github.com:nvie/vim-flake8.git vim/bundle/vim-flake8
git submodule addgit@github.com:rodjek/vim-puppet.git vim/bundle/vim-puppet
git submodule addhttps://github.com/dcosson/vimux-nose-test2 vim/bundle/vimux-nose-test2
git submodule addhttps://github.com/scrooloose/syntastic.git vim/bundle/syntastic
git submodule addgit@github.com:Lokaltog/powerline.git vim/bundle/powerline
git submodule addgit@github.com:tpope/vim-fugitive.git vim/bundle/vim-fugitive
